-- The database will be generated when you run the application, however, sometimes, the subscriptions table won't be generated
CREATE TABLE IF NOT EXISTS public.subscriptions
(
    subscription_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    is_trial_period boolean NOT NULL,
    next_billing_date date,
    start_date date,
    tier character varying(255) COLLATE pg_catalog."default",
    subscription_price integer,
    CONSTRAINT subscriptions_tier_check CHECK (tier::text = ANY (ARRAY['SD'::character varying, 'HD'::character varying, 'UHD'::character varying, 'MONTHLY_PRICE'::character varying]::text[]))
);

-- To add the verification token, please run
update users set activation_token = '1234a' where user_id = 1

-- The URL to our front-end is http://localhost:8080/home
